DEFAULT_TEST_PUBLIC_KEY_PEM = """-----BEGIN PUBLIC KEY-----
MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEH6f4+oId//UeNYnEqi+6EqRKg+fW
V0lpZNmC4u+0b8wdvh6+r0jUYGiQJNiXGcYXiqvQvQgw5HtP7XjtWW09hg==
-----END PUBLIC KEY-----
"""
